### ISSUE TITLE
Spec website down

### ISSUE THREAD

**Issue by 0xdeafcafe** [JamesNK/Newtonsoft.Dson#2]
The spec website is down, if you still have the source, maybe you could put it on a GitHub pages site for the project? Would love to have had a read though haha.

**Comment by aluanhaddad** [comment]
@0xdeafcafe https://vpzomtrrfrt.github.io/DSON/

**Comment by Tay77** [comment]
I need an upgrade for Dson

**Comment by Tay77** [comment]
It is easy to download from Apple iTunes
